import { useState } from 'react';
import { reportAPI, kpiAPI } from '../services/api';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

/* --- download helpers --- */
const downloadJSON = (data, filename) => {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
};

const downloadCSV = (rows, headers, filename) => {
  const csv = [
    headers.join(','),
    ...rows.map(r => headers.map(h => '"' + String(r[h] != null ? r[h] : '').replace(/"/g, '""') + '"').join(','))
  ].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
};

/* --- sanitize text for jsPDF (Helvetica only supports basic Latin) --- */
function safe(text) {
  if (text == null) return '-';
  return String(text)
    .replace(/[\u2014\u2013]/g, '-')  // em-dash, en-dash
    .replace(/[\u2018\u2019]/g, "'")  // smart quotes
    .replace(/[\u2026]/g, '...')       // ellipsis
    .replace(/[\u201C\u201D]/g, '"')  // smart double quotes
    .replace(/[^\x00-\x7F]/g, '');    // remove any other non-ASCII
}

/* --- PDF color palette --- */
const CLR = {
  primary: [124, 58, 237],
  accent: [139, 92, 246],
  bg: [255, 255, 255],
  headerBg: [124, 58, 237],
  headerText: [255, 255, 255],
  text: [30, 30, 30],
  muted: [120, 120, 120],
  lightGray: [245, 245, 245],
  border: [220, 220, 220],
  white: [255, 255, 255],
};

/* --- shared table config --- */
function getTableConfig(startY) {
  return {
    startY,
    theme: 'grid',
    styles: {
      fontSize: 8,
      textColor: CLR.text,
      cellPadding: 3,
      lineColor: CLR.border,
      lineWidth: 0.15,
      font: 'helvetica',
    },
    headStyles: {
      fillColor: CLR.headerBg,
      textColor: CLR.headerText,
      fontStyle: 'bold',
      fontSize: 8,
    },
    alternateRowStyles: {
      fillColor: CLR.lightGray,
    },
    margin: { left: 14, right: 14, top: 30 },
  };
}

/* --- cover page --- */
function drawCover(doc, line1, line2, subtitle, author) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();

  // White background
  doc.setFillColor(...CLR.bg);
  doc.rect(0, 0, w, h, 'F');

  // Purple header band
  doc.setFillColor(...CLR.primary);
  doc.rect(0, 0, w, 80, 'F');

  // Brand
  doc.setTextColor(...CLR.white);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('ReqTrace', 20, 25);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('ML-Based Requirement Classification', 20, 32);

  // Title
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.text(safe(line1), 20, 55);
  if (line2) {
    doc.setFontSize(26);
    doc.text(safe(line2), 20, 67);
  }

  // Subtitle below band
  doc.setTextColor(...CLR.muted);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(safe(subtitle), 20, 98);

  // Metadata
  doc.setFillColor(...CLR.lightGray);
  doc.rect(20, 115, w - 40, 40, 'F');
  doc.setDrawColor(...CLR.border);
  doc.rect(20, 115, w - 40, 40, 'S');

  doc.setFontSize(8);
  doc.setTextColor(...CLR.muted);
  doc.text('GENERATED BY', 28, 127);
  doc.text('DATE', 28, 141);
  doc.text('AUTHOR', 110, 127);
  doc.text('FORMAT', 110, 141);

  doc.setTextColor(...CLR.text);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('ReqTrace', 28, 133);
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), 28, 147);
  doc.text(safe(author) || 'System', 110, 133);
  doc.text('PDF', 110, 147);

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(...CLR.muted);
  doc.setFont('helvetica', 'normal');
  doc.text('Auto-generated by ReqTrace - ML Requirement Classification & Traceability Tool', 20, h - 15);

  doc.addPage();
}

/* --- page header (called on each content page) --- */
function drawPageHeader(doc, title) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...CLR.primary);
  doc.rect(0, 0, w, 18, 'F');
  doc.setTextColor(...CLR.white);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(safe(title), 14, 12);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('ReqTrace | ' + new Date().toLocaleDateString(), w - 14, 12, { align: 'right' });
}

/* --- page footers --- */
function drawFooters(doc) {
  const total = doc.internal.getNumberOfPages();
  for (let i = 2; i <= total; i++) {
    doc.setPage(i);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.setDrawColor(...CLR.border);
    doc.line(14, h - 14, w - 14, h - 14);
    doc.setTextColor(...CLR.muted);
    doc.setFontSize(7);
    doc.text('Page ' + (i - 1) + ' of ' + (total - 1), w / 2, h - 8, { align: 'center' });
  }
}

/* --- section title --- */
function drawSection(doc, title, y) {
  doc.setFillColor(...CLR.lightGray);
  doc.rect(14, y - 4, doc.internal.pageSize.getWidth() - 28, 10, 'F');
  doc.setFillColor(...CLR.primary);
  doc.rect(14, y - 4, 3, 10, 'F');
  doc.setTextColor(...CLR.text);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(safe(title), 22, y + 3);
  return y + 14;
}

/* --- stat box --- */
function drawStat(doc, label, value, x, y, w) {
  doc.setFillColor(...CLR.lightGray);
  doc.rect(x, y, w, 20, 'F');
  doc.setDrawColor(...CLR.border);
  doc.rect(x, y, w, 20, 'S');
  doc.setTextColor(...CLR.muted);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(safe(label).toUpperCase(), x + 4, y + 8);
  doc.setTextColor(...CLR.text);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(String(value), x + 4, y + 17);
}


/* ============================================
   SRS PDF
   ============================================ */
function buildSRSPdf(data, author) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();

  drawCover(doc, 'Software Requirements', 'Specification', 'FR and NFR requirements with ML classification', author);

  // Summary page
  drawPageHeader(doc, 'SRS Report - Summary');

  let y = 26;
  const sw = (w - 42) / 4;
  const allReqs = [...(data.functional || []), ...(data.nonFunctional || [])];
  const ambCount = allReqs.filter(r => r.ambiguityFlag).length;

  drawStat(doc, 'Total', data.total || allReqs.length, 14, y, sw);
  drawStat(doc, 'Functional (FR)', (data.functional || []).length, 14 + sw + 4.5, y, sw);
  drawStat(doc, 'Non-Functional', (data.nonFunctional || []).length, 14 + (sw + 4.5) * 2, y, sw);
  drawStat(doc, 'Ambiguous', ambCount, 14 + (sw + 4.5) * 3, y, sw);

  y += 30;

  // FR table
  if ((data.functional || []).length > 0) {
    y = drawSection(doc, 'Functional Requirements (FR)', y);

    doc.autoTable({
      ...getTableConfig(y),
      head: [['ID', 'Requirement Text', 'Confidence', 'Priority', 'Ambiguous']],
      body: data.functional.map(r => [
        safe(r.requirementId),
        safe(r.text).slice(0, 90),
        r.confidenceScore != null ? (r.confidenceScore * 100).toFixed(0) + '%' : '-',
        safe(r.priority) || 'Medium',
        r.ambiguityFlag ? 'Yes' : 'No',
      ]),
      columnStyles: {
        0: { cellWidth: 28 },
        2: { cellWidth: 20, halign: 'center' },
        3: { cellWidth: 18, halign: 'center' },
        4: { cellWidth: 20, halign: 'center' },
      },
      didDrawPage: function(d) {
        if (d.pageNumber > 1) {
          drawPageHeader(doc, 'SRS Report - Functional Requirements');
        }
      },
    });

    y = doc.lastAutoTable.finalY + 10;
  }

  // NFR table
  if ((data.nonFunctional || []).length > 0) {
    const pageH = doc.internal.pageSize.getHeight();
    if (y > pageH - 50) {
      doc.addPage();
      drawPageHeader(doc, 'SRS Report - Non-Functional Requirements');
      y = 26;
    } else {
      y = drawSection(doc, 'Non-Functional Requirements (NFR)', y);
    }

    doc.autoTable({
      ...getTableConfig(y),
      head: [['ID', 'Requirement Text', 'Category', 'Confidence', 'Ambiguous']],
      body: data.nonFunctional.map(r => [
        safe(r.requirementId),
        safe(r.text).slice(0, 90),
        safe(r.category) || 'General',
        r.confidenceScore != null ? (r.confidenceScore * 100).toFixed(0) + '%' : '-',
        r.ambiguityFlag ? 'Yes' : 'No',
      ]),
      columnStyles: {
        0: { cellWidth: 28 },
        2: { cellWidth: 22, halign: 'center' },
        3: { cellWidth: 20, halign: 'center' },
        4: { cellWidth: 20, halign: 'center' },
      },
      didDrawPage: function(d) {
        if (d.pageNumber > 1) {
          drawPageHeader(doc, 'SRS Report - Non-Functional Requirements');
        }
      },
    });
  }

  if (allReqs.length === 0) {
    doc.setTextColor(...CLR.muted);
    doc.setFontSize(11);
    doc.text('No requirements found. Upload requirements to generate the report.', 14, y + 10);
  }

  drawFooters(doc);
  doc.save('SRS-Report-' + new Date().toISOString().slice(0, 10) + '.pdf');
}


/* ============================================
   Traceability PDF
   ============================================ */
function buildTraceabilityPdf(data, author) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();

  drawCover(doc, 'Traceability Matrix', 'Report', 'Requirement-to-test-case traceability mapping', author);

  drawPageHeader(doc, 'Traceability Matrix');
  let y = 26;

  const links = data.links || [];
  const validated = links.filter(l => l.validationStatus === 'Validated').length;
  const pending = links.filter(l => l.validationStatus === 'Pending').length;
  const missing = links.filter(l => l.validationStatus === 'Missing').length;

  const sw = (w - 42) / 4;
  drawStat(doc, 'Total Links', links.length, 14, y, sw);
  drawStat(doc, 'Validated', validated, 14 + sw + 4.5, y, sw);
  drawStat(doc, 'Pending', pending, 14 + (sw + 4.5) * 2, y, sw);
  drawStat(doc, 'Missing', missing, 14 + (sw + 4.5) * 3, y, sw);

  y += 30;
  y = drawSection(doc, 'Traceability Links', y);

  if (links.length > 0) {
    doc.autoTable({
      ...getTableConfig(y),
      head: [['#', 'Req ID', 'Requirement Text', 'Test ID', 'Test Case Description', 'Status']],
      body: links.map((l, i) => [
        i + 1,
        safe(l.requirementId?.requirementId),
        safe(l.requirementId?.text).slice(0, 55),
        safe(l.testCaseId?.testCaseId),
        safe(l.testCaseId?.description).slice(0, 55),
        safe(l.validationStatus) || 'Pending',
      ]),
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 25 },
        3: { cellWidth: 25 },
        5: { cellWidth: 20, halign: 'center' },
      },
      didDrawPage: function(d) {
        if (d.pageNumber > 1) {
          drawPageHeader(doc, 'Traceability Matrix');
        }
      },
    });
  } else {
    doc.setTextColor(...CLR.muted);
    doc.setFontSize(11);
    doc.text('No traceability links found. Link requirements to test cases first.', 14, y + 5);
  }

  drawFooters(doc);
  doc.save('Traceability-Report-' + new Date().toISOString().slice(0, 10) + '.pdf');
}


/* ============================================
   KPI PDF
   ============================================ */
function buildKpiPdf(data, author) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.getWidth();

  drawCover(doc, 'KPI Analytics', 'Report', 'Quality metrics, coverage, and validation statistics', author);

  drawPageHeader(doc, 'KPI Analytics Report');
  let y = 26;

  const sw = (w - 38) / 3;
  drawStat(doc, 'Total Requirements', data.totalRequirements || 0, 14, y, sw);
  drawStat(doc, 'Functional (FR)', data.functionalRequirements || 0, 14 + sw + 5, y, sw);
  drawStat(doc, 'Non-Functional (NFR)', data.nonFunctionalRequirements || 0, 14 + (sw + 5) * 2, y, sw);

  y += 28;
  drawStat(doc, 'Ambiguity Rate', (data.ambiguityRate || 0) + '%', 14, y, sw);
  drawStat(doc, 'Traceability Coverage', (data.traceabilityCoverage || 0) + '%', 14 + sw + 5, y, sw);
  drawStat(doc, 'Validation Coverage', (data.validationCoverage || 0) + '%', 14 + (sw + 5) * 2, y, sw);

  y += 28;
  drawStat(doc, 'Total Test Cases', data.totalTestCases || 0, 14, y, sw);
  drawStat(doc, 'Total Trace Links', data.totalTraceLinks || 0, 14 + sw + 5, y, sw);
  drawStat(doc, 'Validated Links', data.validatedLinks || 0, 14 + (sw + 5) * 2, y, sw);

  y += 35;

  // Trend data
  if (data.trendData && data.trendData.length > 0) {
    y = drawSection(doc, '7-Day Trend Data', y);

    doc.autoTable({
      ...getTableConfig(y),
      head: [['Date', 'Total Reqs', 'Ambiguous', 'Ambiguity Rate']],
      body: data.trendData.map(t => [
        t.date,
        t.total,
        t.ambiguous,
        (t.rate * 100).toFixed(1) + '%',
      ]),
    });

    y = doc.lastAutoTable.finalY + 12;
  }

  // Category breakdown
  const cats = data.categories || {};
  if (Object.keys(cats).length > 0) {
    const pageH = doc.internal.pageSize.getHeight();
    if (y > pageH - 60) {
      doc.addPage();
      drawPageHeader(doc, 'KPI Analytics - Categories');
      y = 26;
    }

    y = drawSection(doc, 'Category Breakdown', y);

    doc.autoTable({
      ...getTableConfig(y),
      head: [['Category', 'Count', 'Percentage']],
      body: Object.entries(cats).map(([cat, count]) => [
        safe(cat),
        count,
        ((count / (data.totalRequirements || 1)) * 100).toFixed(1) + '%',
      ]),
    });
  }

  drawFooters(doc);
  doc.save('KPI-Report-' + new Date().toISOString().slice(0, 10) + '.pdf');
}


/* --- Report Card UI --- */
function ReportCard({ icon, title, description, actions }) {
  return (
    <div className="glass-card hover:border-primary/30 border border-transparent transition-all group">
      <div className="flex items-start gap-4">
        <div className="w-10 h-10 rounded-xl bg-primary/15 flex items-center justify-center text-primary text-lg shrink-0 group-hover:bg-primary/25 transition-colors">
          {icon}
        </div>
        <div className="flex-1">
          <h3 className="font-semibold text-base-content">{title}</h3>
          <p className="text-xs text-base-content/40 mt-1 mb-4">{description}</p>
          <div className="flex gap-2 flex-wrap">
            {actions.map((action, i) => (
              <button
                key={i}
                onClick={action.fn}
                disabled={action.loading}
                className={
                  'btn btn-xs gap-1.5 ' +
                  (action.primary
                    ? 'btn-primary shadow-lg shadow-primary/20'
                    : 'btn-outline border-white/10 hover:border-primary/50')
                }
              >
                {action.loading ? (
                  <span className="loading loading-spinner loading-xs"></span>
                ) : (
                  action.label
                )}
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}


/* --- Main Page --- */
export default function ReportsPage() {
  const [loading, setLoading] = useState({});
  const setLoad = (key, val) => setLoading(prev => ({ ...prev, [key]: val }));

  const getUserName = () => {
    try { return JSON.parse(localStorage.getItem('user') || '{}').name || 'User'; }
    catch { return 'User'; }
  };

  // ---- SRS ----
  const exportSRSPdf = async () => {
    setLoad('srs-pdf', true);
    try {
      const res = await reportAPI.srs();
      buildSRSPdf(res.data.data, getUserName());
      toast.success('SRS PDF downloaded!');
    } catch (err) {
      console.error('SRS PDF error:', err);
      toast.error('SRS PDF export failed. See console for details.');
    } finally { setLoad('srs-pdf', false); }
  };

  const exportSRSJson = async () => {
    setLoad('srs-json', true);
    try {
      const res = await reportAPI.srs();
      downloadJSON(res.data.data, 'srs-report-' + Date.now() + '.json');
      toast.success('SRS JSON downloaded!');
    } catch (err) {
      console.error('SRS JSON error:', err);
      toast.error('Export failed');
    } finally { setLoad('srs-json', false); }
  };

  const exportSRSCsv = async () => {
    setLoad('srs-csv', true);
    try {
      const res = await reportAPI.srs();
      const all = [...(res.data.data.functional || []), ...(res.data.data.nonFunctional || [])];
      downloadCSV(all.map(r => ({
        ID: r.requirementId, Type: r.classification, Text: r.text,
        Confidence: r.confidenceScore, Category: r.category, Priority: r.priority,
        Ambiguous: r.ambiguityFlag ? 'Yes' : 'No', Status: r.status,
      })), ['ID', 'Type', 'Text', 'Confidence', 'Category', 'Priority', 'Ambiguous', 'Status'], 'srs-report-' + Date.now() + '.csv');
      toast.success('SRS CSV downloaded!');
    } catch (err) {
      console.error('SRS CSV error:', err);
      toast.error('Export failed');
    } finally { setLoad('srs-csv', false); }
  };

  // ---- Traceability ----
  const exportTracePdf = async () => {
    setLoad('trace-pdf', true);
    try {
      const res = await reportAPI.traceability();
      buildTraceabilityPdf(res.data.data, getUserName());
      toast.success('Traceability PDF downloaded!');
    } catch (err) {
      console.error('Trace PDF error:', err);
      toast.error('Traceability PDF export failed. See console for details.');
    } finally { setLoad('trace-pdf', false); }
  };

  const exportTraceJson = async () => {
    setLoad('trace-json', true);
    try {
      const res = await reportAPI.traceability();
      downloadJSON(res.data.data, 'traceability-' + Date.now() + '.json');
      toast.success('Traceability JSON downloaded!');
    } catch (err) {
      console.error('Trace JSON error:', err);
      toast.error('Export failed');
    } finally { setLoad('trace-json', false); }
  };

  const exportTraceCsv = async () => {
    setLoad('trace-csv', true);
    try {
      const res = await reportAPI.traceability();
      const links = res.data.data.links || [];
      downloadCSV(links.map(l => ({
        RequirementID: l.requirementId?.requirementId,
        Requirement: (l.requirementId?.text || '').slice(0, 80),
        TestCaseID: l.testCaseId?.testCaseId,
        TestCase: l.testCaseId?.description,
        Status: l.validationStatus,
      })), ['RequirementID', 'Requirement', 'TestCaseID', 'TestCase', 'Status'], 'traceability-' + Date.now() + '.csv');
      toast.success('Traceability CSV downloaded!');
    } catch (err) {
      console.error('Trace CSV error:', err);
      toast.error('Export failed');
    } finally { setLoad('trace-csv', false); }
  };

  // ---- KPI ----
  const exportKpiPdf = async () => {
    setLoad('kpi-pdf', true);
    try {
      const res = await kpiAPI.get();
      buildKpiPdf(res.data.data, getUserName());
      toast.success('KPI PDF downloaded!');
    } catch (err) {
      console.error('KPI PDF error:', err);
      toast.error('KPI PDF export failed. See console for details.');
    } finally { setLoad('kpi-pdf', false); }
  };

  const exportKpiJson = async () => {
    setLoad('kpi-json', true);
    try {
      const res = await kpiAPI.get();
      downloadJSON({ ...res.data.data, generatedAt: new Date(), title: 'KPI Analytics Report' }, 'kpi-report-' + Date.now() + '.json');
      toast.success('KPI JSON downloaded!');
    } catch (err) {
      console.error('KPI JSON error:', err);
      toast.error('Export failed');
    } finally { setLoad('kpi-json', false); }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">Reports</h1>
        <p className="text-base-content/40 text-sm">Generate and download professional reports in PDF, JSON, or CSV</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <ReportCard
          icon={<span>📋</span>}
          title="SRS Report"
          description="Software Requirements Specification - all FR and NFR requirements with ML classification, confidence scores, and ambiguity analysis"
          actions={[
            { label: 'Download PDF', fn: exportSRSPdf, loading: loading['srs-pdf'], primary: true },
            { label: 'JSON', fn: exportSRSJson, loading: loading['srs-json'] },
            { label: 'CSV', fn: exportSRSCsv, loading: loading['srs-csv'] },
          ]}
        />
        <ReportCard
          icon={<span>🔗</span>}
          title="Traceability Matrix"
          description="Complete requirement-to-test-case traceability mapping with validation status for audit compliance"
          actions={[
            { label: 'Download PDF', fn: exportTracePdf, loading: loading['trace-pdf'], primary: true },
            { label: 'JSON', fn: exportTraceJson, loading: loading['trace-json'] },
            { label: 'CSV', fn: exportTraceCsv, loading: loading['trace-csv'] },
          ]}
        />
        <ReportCard
          icon={<span>📊</span>}
          title="KPI Analytics Report"
          description="Quality metrics including ambiguity rate, traceability coverage, validation statistics, and 7-day trends"
          actions={[
            { label: 'Download PDF', fn: exportKpiPdf, loading: loading['kpi-pdf'], primary: true },
            { label: 'JSON', fn: exportKpiJson, loading: loading['kpi-json'] },
          ]}
        />

        <div className="glass-card border border-primary/20 bg-primary/5">
          <h3 className="font-semibold text-primary mb-3">About Reports</h3>
          <ul className="space-y-2 text-xs text-base-content/60">
            <li className="flex items-start gap-2">
              <span className="text-primary mt-0.5">*</span>
              <span><strong className="text-base-content/80">PDF Reports</strong> - Professional branded documents ready for stakeholder review</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-primary mt-0.5">*</span>
              <span><strong className="text-base-content/80">SRS Report</strong> - Full requirements spec with ML classification details</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-primary mt-0.5">*</span>
              <span><strong className="text-base-content/80">Traceability</strong> - Req-to-test case matrix for audit trails</span>
            </li>
            <li className="flex items-start gap-2">
              <span className="text-primary mt-0.5">*</span>
              <span><strong className="text-base-content/80">KPI Report</strong> - Analytics snapshot with all quality metrics</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}
